name: CD - Deploy ParkingStatus

on:
  push:
    branches: [ test ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/parking-status:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USER }}/parking-status:latest

      - name: SSH into EC2 and redeploy with docker-compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/parking-status
            docker-compose down -v
            docker image prune -f
            docker-compose pull
            docker-compose up --build -d
